### **Welcome to the Python Basics Course! 🦁**

As a start we take the opportunity to emphasize on the importance of understanding **documentation** when using different libraries.
Example of useful documentation for Pandas 🐼  Library: https://pandas.pydata.org/docs/index.html

In [31]:
import pandas as pd
import seaborn as sns

# Load the data

tips_df = sns.load_dataset("tips")
#add a column with date
tips_df['date']=pd.date_range(start='2025-01-01', periods=len(tips_df), freq='D')

In [32]:
tips_df.head()

   total_bill   tip     sex smoker  day    time  size       date
0       16.99  1.01  Female     No  Sun  Dinner     2 2025-01-01
1       10.34  1.66    Male     No  Sun  Dinner     3 2025-01-02
2       21.01  3.50    Male     No  Sun  Dinner     3 2025-01-03
3       23.68  3.31    Male     No  Sun  Dinner     2 2025-01-04
4       24.59  3.61  Female     No  Sun  Dinner     4 2025-01-05

In [33]:
#check data types
tips_df.dtypes

total_bill           float64
tip                  float64
sex                 category
smoker              category
day                 category
time                category
size                   int64
date          datetime64[ns]
dtype: object

# **↩ Changing Column Names**

In [78]:
#checking all column names
tips_df.columns

Index(['total_bill', 'tip', 'sex', 'smoker', 'day', 'time', 'size', 'date',
       'year_month', 'year'],
      dtype='object')

In [81]:
#change column name size to be more intuitive
tips_df.rename(columns={'size':'party_size'},inplace=True)

In [83]:
tips_df

,total_bill,tip,sex,smoker,day,time,party_size,date,year_month,year
0,16.99,1.01,Female,No,Sun,Dinner,2,2025-01-01,2025-01,2025
1,10.34,1.66,Male,No,Sun,Dinner,3,2025-01-02,2025-01,2025
2,21.01,3.50,Male,No,Sun,Dinner,3,2025-01-03,2025-01,2025
3,23.68,3.31,Male,No,Sun,Dinner,2,2025-01-04,2025-01,2025
4,24.59,3.61,Female,No,Sun,Dinner,4,2025-01-05,2025-01,2025
...,...,...,...,...,...,...,...,...,...,...
239,29.03,5.92,Male,No,Sat,Dinner,3,2025-08-28,2025-08,2025
240,27.18,2.00,Female,Yes,Sat,Dinner,2,2025-08-29,2025-08,2025
241,22.67,2.00,Male,Yes,Sat,Dinner,2,2025-08-30,2025-08,2025
242,17.82,1.75,Male,No,Sat,Dinner,2,2025-08-31,2025-08,2025
243,18.78,3.00,Female,No,Thur,Dinner,2,2025-09-01,2025-09,2025

# **↩ Changing data types**

In [62]:
#check distinct values in size
tips_df['size'].unique()

['2', '3', '4', '1', '6', '5']
Categories (6, object): ['1', '2', '3', '4', '5', '6']

In [63]:
#changing size to str
tips_df['size']=tips_df['size'].astype('category')
tips_df.dtypes

total_bill           float64
tip                  float64
sex                 category
smoker              category
day                 category
time                category
size                category
date          datetime64[ns]
year_month         period[M]
year                   int32
dtype: object

In [65]:
tips_df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
date          0
year_month    0
year          0
dtype: int64

# **⏲** **Changing daily data to monthly/yearly**

In [34]:
# what are the monthly sales ?
#create a new column with year-month
tips_df['year_month']=tips_df['date'].dt.to_period('M')
tips_df.sort_values(by='date',inplace=True)
tips_df

     total_bill   tip     sex smoker   day    time  size       date year_month
0         16.99  1.01  Female     No   Sun  Dinner     2 2025-01-01    2025-01
1         10.34  1.66    Male     No   Sun  Dinner     3 2025-01-02    2025-01
2         21.01  3.50    Male     No   Sun  Dinner     3 2025-01-03    2025-01
3         23.68  3.31    Male     No   Sun  Dinner     2 2025-01-04    2025-01
4         24.59  3.61  Female     No   Sun  Dinner     4 2025-01-05    2025-01
..          ...   ...     ...    ...   ...     ...   ...        ...        ...
239       29.03  5.92    Male     No   Sat  Dinner     3 2025-08-28    2025-08
240       27.18  2.00  Female    Yes   Sat  Dinner     2 2025-08-29    2025-08
241       22.67  2.00    Male    Yes   Sat  Dinner     2 2025-08-30    2025-08
242       17.82  1.75    Male     No   Sat  Dinner     2 2025-08-31    2025-08
243       18.78  3.00  Female     No  Thur  Dinner     2 2025-09-01    2025-09

[244 rows x 9 columns]

In [55]:
#monthly sales
monthly_sales=tips_df.groupby('year_month')['total_bill'].sum()
monthly_sales

year_month
2025-01    575.39
2025-02    574.46
2025-03    602.59
2025-04    620.59
2025-05    504.69
2025-06    654.20
2025-07    685.37
2025-08    591.70
2025-09     18.78
Freq: M, Name: total_bill, dtype: float64

In [57]:
monthly_sales.sum()

np.float64(4827.7699999999995)

In [42]:
tips_df['year']=tips_df['date'].dt.year
yearly_sales=tips_df.groupby('year')['total_bill'].sum()
yearly_sales

year
2025    4827.77
Name: total_bill, dtype: float64

# **⚠ Null Values**

In [68]:
#setting tip values >9 to null
tips_df.loc[tips_df['tip']>9,'tip']=None

In [71]:
#fidning null counrts in each column
tips_df.isnull().sum()

total_bill    0
tip           1
sex           0
smoker        0
day           0
time          0
size          0
date          0
year_month    0
year          0
dtype: int64

In [74]:
#replacing null value with 10
tips_df['tip']=tips_df['tip'].fillna(10)

In [75]:
#check to see null value replaced
tips_df.isnull().sum()

total_bill    0
tip           0
sex           0
smoker        0
day           0
time          0
size          0
date          0
year_month    0
year          0
dtype: int64

# ⚖ Group By

In [85]:
#find the sales generated by time of service
tips_df.groupby('time')['total_bill'].sum()

/tmp/ipykernel_11611/2702684033.py:2: FutureWarning: The default of observed=False is deprecated and will be changed to True in a future version of pandas. Pass observed=False to retain current behavior or observed=True to adopt the future default and silence this warning.
  tips_df.groupby('time')['total_bill'].sum()

time
Lunch     1167.47
Dinner    3660.30
Name: total_bill, dtype: float64